### ISSUE TITLE
Update to 1.4.0 fails

### ISSUE THREAD

**Issue by oopiicaa** [ArtemVladimirov/hassio-add-ons#1]
Hey,

update to 1.4.0 is failing:
`The command '/bin/ash -o pipefail -c if [ "${BUILD_ARCH}" = "armhf" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm.tar.gz; elif [ "${BUILD_ARCH}" = "armv7" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm7.tar.gz; elif [ "${BUILD_ARCH}" = "aarch64" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-arm64.tar.gz; elif [ "${BUILD_ARCH}" = "i386" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-386.tar.gz; elif [ "${BUILD_ARCH}" = "amd64" ]; then wget -O broadlinkac2mqtt.tar.gz https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/download/${BUILD_VERSION}/broadlinkac2mqtt-${BUILD_VERSION}-linux-amd64.tar.gz; else echo 'NOT VALID BUILD'; exit 1; fi && tar -xzf broadlinkac2mqtt.tar.gz && rm broadlinkac2mqtt.tar.gz && chmod a+x ./run.sh && mkdir config && apk add --no-cache gcc g++ make && pip3 install --no-cache-dir -U pyyaml' returned a non-zero code: 1`

![Screenshot_2023-07-24-17-39-39-370_io homeassistant companion android-edit](https://github.com/ArtemVladimirov/hassio-add-ons/assets/24246157/cad12c4b-5846-4986-b2a0-ca565c4c3912)

**Comment by ArtemVladimirov** [comment]
Fixed...
https://github.com/ArtemVladimirov/hassio-add-ons/commit/ea3eb44c9d30087e716cae077dd6bee09adb640e

**Comment by oopiicaa** [comment]
Thanks, I succesfully updated it, but the add-on does not start for me now. Reported in the core repo.
