### ISSUE TITLE
2022 Vortex AC

### ISSUE THREAD

**Issue by kr3at0r** [ArtemVladimirov/hassio-add-ons#5]
Hi,

I have 3 Vortex AC units (2 from 2016 and 1 from 2022)
I had no issues connecting the ones from 2016 but unfortunately the one from 2022 is not connecting:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
{"level":"debug","time":"2023-09-13T14:33:38Z","caller":"/app/broadlinkac2mqtt/config/config.go:47","message":"Start reading a config file"}
{"level":"error","error":"read udp 172.30.33.4:60992->192.168.0.49:80: i/o timeout","time":"2023-09-13T14:33:48Z","caller":"/app/broadlinkac2mqtt/app/webClient/client.go:43","message":"Failed to read the response"}
{"level":"error","error":"read udp 172.30.33.4:60992->192.168.0.49:80: i/o timeout","input":{"Command":101,"Payload":"RTRS5/ku2pWDRJMINe+abftpLcNwuQRDrFzWP7tTrfoIgUyn+M9BcQAyjlcMO4bJTQVwhEmjieKa4QRUNqBb3dwCwWGvEyXofhmw99HOBo0=","Mac":"ec0bae566d7a"},"device":"ec0bae566d7a","time":"2023-09-13T14:33:48Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:665","message":"failed to send a command"}
{"level":"error","error":"read udp 172.30.33.4:60992->192.168.0.49:80: i/o timeout","input":{"Mac":"ec0bae566d7a"},"time":"2023-09-13T14:33:48Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:139","message":"failed to send command"}
{"level":"error","error":"read udp 172.30.33.4:60992->192.168.0.49:80: i/o timeout","device":"ec0bae566d7a","time":"2023-09-13T14:33:48Z","caller":"/app/broadlinkac2mqtt/main.go:156","message":"Failed to Auth device ec0bae566d7a. Reconnect in 3 seconds..."}

Any idea what I can do?

**Comment by ArtemVladimirov** [comment]
I think the device uses a different protocol. I don't have any information on another protocol, so most likely the device is not supported by this application.
