### ISSUE TITLE
Greenwind inverter ac

### ISSUE THREAD

**Issue by rdaguerre** [ArtemVladimirov/hassio-add-ons#9]
Hi, my log is:

{"level":"error","error":"ErrorInvalidResultPacket","input":{"Command":106,"Payload":"Fs0Rbe/ji/q6hXD8QcD7vg==","Mac":"24dfa7b5ba42"},"time":"2024-03-13T01:46:31Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:232","message":"Checksum is incorrect"}
{"level":"error","device":"24dfa7b5ba42","time":"2024-03-13T01:46:31Z","caller":"/app/broadlinkac2mqtt/app/service/service.go:1134","message":"failed to get ambient temperature"}

Any idea to resolve.
Thanks

**Comment by ArtemVladimirov** [comment]
I think the device uses a different protocol. I don't have any information on another protocol, so most likely the device is not supported by this application.

**Comment by rdaguerre** [comment]
i use intelligent AC. any idea where can i start? thanks
